### ISSUE TITLE
AggregateException when training detection projects

### ISSUE THREAD

**Issue by rhoegen** [vladkol/CustomVision.COCO#1]
Hi,

first of all thank you for sharing this project. It really helps creating custom vision projects without manual effort.

The creation of classification projects as specified in the example works like a charm. When trying to create a detection project with the -d flag, i always get a "AggregateException" when the program starts to upload images. Some images get uploaded to the project but it is not enough to start the training. I am using the 2017 Training data (http://images.cocodataset.org/annotations/annotations_trainval2017.zip)

Have you experienced this issue before and can you guide me the right way to fix it?

Thanks and best regards

**Comment by rhoegen** [comment]
After testing around a little bit i can provide a bit more information:

- The category "people" can be trained with 5000 images with no problem
- all other categories I have tested so far (bottle, chair, cup) each crash after exactly 64 images were uploaded and tagged

**Comment by vladkol** [comment]
It seems the issue has been resolved
